version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: bash -c "rm -f tmp/pids/server.pid && rails db:migrate && bundle exec rails s -b '0.0.0.0'"
    ports:
      - "3000:3000"
    depends_on:
      - mysql
      - redis
    volumes:
      - .:/app
    environment:
      SECRET_KEY: my_secret
      REDIS_URL: redis://redis:6379/0
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      RAILS_MAX_THREADS: 5
      DATABASE_USER: user
      DATABASE_PASSWORD: pass
      MYSQL_DATABASE: blogs

  sidekiq:
    build:
      context: .
      dockerfile: Dockerfile
    command: bundle exec sidekiq
    volumes:
      - ".:/app"
    depends_on:
      - redis
      - mysql
    environment:
      REDIS_URL: redis://redis:6379/0
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      RAILS_MAX_THREADS: 5
      DATABASE_USER: user
      DATABASE_PASSWORD: pass
      MYSQL_DATABASE: blogs

      

  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
      MYSQL_DATABASE: blogs
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql


  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data


volumes:
  redis-data:
  mysql_data: